const challengeData = [
    { day: 1, ko: "지갑 속의 필요 없는 영수증과 안 쓰는 카드를 비우세요.", en: "Clear out old receipts and unused cards from your wallet." },
    { day: 2, ko: "스마트폰 메인 화면의 앱을 절반으로 줄여보세요.", en: "Reduce the apps on your home screen by half." },
    { day: 3, ko: "1년 동안 입지 않은 옷 한 벌을 기부하거나 버리세요.", en: "Donate or discard one piece of clothing you haven't worn in a year." },
    { day: 4, ko: "책상 위, 당장 필요 없는 모든 물건을 서랍에 넣으세요.", en: "Clear your desk. Put everything not immediately needed into drawers." },
    { day: 5, ko: "오늘 하루, SNS 알림을 모두 끄고 지내보세요.", en: "Turn off all social media notifications for today." },
    { day: 6, ko: "유통기한이 지난 화장품이나 약을 찾아 버리세요.", en: "Discard expired cosmetics or medicines." },
    { day: 7, ko: "사진첩에서 흐릿하거나 중복된 사진 10장을 지우세요.", en: "Delete 10 blurry or duplicate photos from your gallery." },
    { day: 8, ko: "가방 속을 전부 꺼내 먼지를 털고, 꼭 필요한 것만 다시 넣으세요.", en: "Empty your bag, shake out the dust, and put back only essentials." },
    { day: 9, ko: "냉장고를 열어 오래된 식재료 하나를 비우세요.", en: "Open your fridge and discard one old ingredient." },
    { day: 10, ko: "이메일 함의 '구독(뉴스레터/광고)' 메일 하나를 수신 거부하세요.", en: "Unsubscribe from one newsletter or promotional email." },
    { day: 11, ko: "신발장을 정리하고 낡은 신발 한 켤레와 작별하세요.", en: "Organize your shoe rack and say goodbye to one pair of worn-out shoes." },
    { day: 12, ko: "잠들기 1시간 전, 전자기기를 멀리하세요.", en: "Stay away from electronics for 1 hour before sleep." },
    { day: 13, ko: "펜 꽂이에 있는 나오지 않는 펜을 모두 골라내세요.", en: "Discard all dried-out pens from your holder." },
    { day: 14, ko: "카카오톡/메신저의 불필요한 단체방 1곳을 나가세요.", en: "Leave one unnecessary group chat window." },
    { day: 15, ko: "오늘 하루, '나중에 해야지'라는 말을 '지금 하자'로 바꿔보세요.", en: "Today, change 'I'll do it later' to 'I'll do it now'." },
    { day: 16, ko: "욕실의 낡은 칫솔이나 빈 샴푸 통을 비우세요.", en: "Discard old toothbrushes or empty shampoo bottles." },
    { day: 17, ko: "바탕화면의 파일을 폴더 하나로 정리하세요.", en: "Organize your desktop files into a single folder." },
    { day: 18, ko: "양말 서랍을 열어 짝이 없거나 구멍 난 양말을 버리세요.", en: "Discard mismatched or holey socks." },
    { day: 19, ko: "오늘 한 끼는 자극적인 양념 없이 담백하게 드세요.", en: "Eat one meal today with mild seasoning and simple ingredients." },
    { day: 20, ko: "오랫동안 연락하지 않은 연락처 3개를 지우세요.", en: "Delete 3 contacts you haven't been in touch with for a long time." },
    { day: 21, ko: "집안의 '잡동사니 서랍' 하나를 10분간 정리하세요.", en: "Spend 10 minutes organizing one 'junk drawer'." },
    { day: 22, ko: "악세사리 함에서 1년 이상 착용하지 않은 것을 비우세요.", en: "Remove accessories you haven't worn in over a year." },
    { day: 23, ko: "오늘 하루, 불평하는 말을 멈춰보세요.", en: "Try to stop complaining for just one day." },
    { day: 24, ko: "침실에 있는 잡동사니를 거실로 옮겨 침실을 순수하게 만드세요.", en: "Move clutter from the bedroom to the living room to purify your sleep space." },
    { day: 25, ko: "지갑이나 주머니에 있는 동전을 모아 기부 저금통에 넣으세요.", en: "Collect coins from your wallet/pocket and put them in a donation jar." },
    { day: 26, ko: "사용 설명서나 보증서 중 기기가 없는 종이들을 버리세요.", en: "Throw away manuals or warranties for devices you no longer own." },
    { day: 27, ko: "오늘 산 물건의 영수증을 받지 않거나 바로 버리세요.", en: "Refuse the receipt or discard it immediately after purchase today." },
    { day: 28, ko: "생각만 하고 실천하지 못한 계획 하나를 목록에서 지우세요.", en: "Cross off one plan from your list that you've only thought about." },
    { day: 29, ko: "나를 괴롭히는 과거의 기억 하나를 종이에 적어 찢어버리세요.", en: "Write down one painful memory and tear up the paper." },
    { day: 30, ko: "지난 29일간 비워낸 공간을 가만히 바라보는 시간을 가지세요.", en: "Spend time quietly observing the space you've cleared over the last 29 days." }
];
